name: Comment on PR Closure

on:
  pull_request_target:
    types:
      - closed

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR Closure
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            const commentAuthor = context.payload.pull_request.user.login;
            const commentBody = `
              Thank you @${commentAuthor} for your valuable time and contribution in our GameZone ğŸ’—. 
              Letâ€™s build this GameZone together! ğŸ¤ 
              Hoping to see you again with another PR soon ğŸ˜‡. 
              Wishing you all the best on your Open Source journey! ğŸš€
            `;
            await github.issues.createComment({ owner, repo, issue_number: number, body: commentBody });
            console.log(`Commented on the closed PR: ${commentBody.trim()}.`);
